### PR TITLE
Fix: Add option to always show the plus icon (fixes #119)

### LINKED ISSUE #119: Remove plus icon that appears when graphic title is not present
### Subject of the issue
This came up on the [Add completion icon styles PR](https://github.com/cgkineo/adapt-hotgrid/pull/117) so just copying the discussion over...

> This has scope creeped quite some. Please update the title+description or move the icon removal to a different pr+issue. Perhaps the icon should just be configurable rather than removed? It's been there since 2019.

Making the icon configurable would mean we still have the issue of duplicate icons.
icon__duplication

`.hotgrid__item-icon` was added following a project where the clients brand didn't allow for borders around images so another element was needed to apply the state changes (inherit button states). 
no_borders

The current implementation of Hotgrid only supports CSS border states or images states. So unless you do custom CSS to remove the borders the original issue `.hotgrid__item-icon` was trying to solve was half baked. With that in mind, @StuartNicholls/@swashbuck, perhaps it's worth reviewing the display/state options in a separate PR. There is definitely a use case for removing `.hotgrid__item-icon` as this is often requested however a config option to allow for no border with plus icon could be useful?

Other reasons raised:
- This regularly gets requested to be removed in projects.
- It doesn't really communicate that its clickable other than it's similar to Hotgraphic.

### PR DESCRIPTION
**Pull request by swashbuck**
Fix #119 

### Fix
* Adds a new option `_alwaysShowIcon` to show the plus icon
* Update schemas and docs
* Add missing `_isRound` option to readme.

### CODE REVIEW

**Review by kirsty-hames — COMMENTED** [review]
Thanks for picking this up @swashbuck. Referring back to the original ticket raised, I thought the consensus was to hide the plus icon by default and this would only be displayed if the config was enabled. 

So if `"_alwaysShowIcon": false`, no plus icon would display regardless of item `title`. I think the use of 'always' in the config gives me the impression it's all or nothing but that might just be me :)

**Comment by swashbuck** [comment]
> Referring back to the original ticket raised, I thought the consensus was to hide the plus icon by default and this would only be displayed if the config was enabled.

Ok, yep, I could have misread that.

Since this refers to the plus icon, should the setting be `_alwaysShowPlusIcon`? Do we need a config option to hide the completion icon, or will that always be displayed?

**Comment by kirsty-hames** [comment]
> Since this refers to the plus icon, should the setting be `_alwaysShowPlusIcon`? 

Yep that makes sense thanks.

> Do we need a config option to hide the completion icon, or will that always be displayed?

The addition of the completion icon was an accessibility requirement for a visual completion state other than colour so I think this should always be displayed.

**Review by kirsty-hames — APPROVED** [review]
Thanks @swashbuck. Works as expected testing on Mac Safari, FF, Chrome and iPhone.

**Comment by swashbuck** [comment]
Confirming that this works in Legacy AAT.

**Pull request merged**
