### PR TITLE
Fix: Add _classes to hotgrid__item (fixes #143)

### LINKED ISSUE #143: Add _items._classes to the button element
### Subject of the issue
Currently, you can add a class to each Hotgrid item with `_items._classes`. The issue is that the classes are only added to the Hotgrid _popup_. To assist with styling, I would like this to be added to the button as well (`.hotgrid__item-btn`).

### PR DESCRIPTION
**Pull request by swashbuck**
Fix #143 

### Fix
* Adds the `_items._classes` to `.hotgrid__item` to assist with styling.
* Retains the custom class on the Hotgrid popups.

### CODE REVIEW

**Comment by oliverfoster** [comment]
Should probably put it on `.hotgrid__item` and not `.hotgrid__item-btn`

**Comment by swashbuck** [comment]
> Should probably put it on `.hotgrid__item` and not `.hotgrid__item-btn`

Yep, done. I initially had it on `hotgrid__item-btn` since that's where the other classes were (is-round, is-visited, etc).

**Review by oliverfoster — APPROVED** [review]

**Comment by oliverfoster** [comment]
> Yep, done. I initially had it on `hotgrid__item-btn` since that's where the other classes were (is-round, is-visited, etc).

Yea it's curious.

**Comment by kirsty-hames** [comment]
> > Yep, done. I initially had it on `hotgrid__item-btn` since that's where the other classes were (is-round, is-visited, etc).
> 
> Yea it's curious.

I think Hotgrid was based on Hotgraphic initially so this has probably carried over. Hotgraphic appends `_classes` and state classes to the button ([`.hotgraphic__pin`](https://github.com/adaptlearning/adapt-contrib-hotgraphic/blob/d4241ec2bcf965a12e25f30bac1fe071eb56ed50/templates/hotgraphicLayoutPins.jsx#L50) / [`.hotgraphic__tile`](https://github.com/adaptlearning/adapt-contrib-hotgraphic/blob/d4241ec2bcf965a12e25f30bac1fe071eb56ed50/templates/hotgraphicLayoutTiles.jsx#L28)).

**Review by kirsty-hames — COMMENTED** [review]
This works as expected thanks @swashbuck. One thing to note, Hotgraphic has separate `_classes` for [popup](https://github.com/adaptlearning/adapt-contrib-hotgraphic/blob/d4241ec2bcf965a12e25f30bac1fe071eb56ed50/example.json#L38) and [item](https://github.com/adaptlearning/adapt-contrib-hotgraphic/blob/d4241ec2bcf965a12e25f30bac1fe071eb56ed50/example.json#L43). Would we want to do the same here for consistency?

Although I do find it odd that the Hotgraphic popup `_classes` is associated with the graphic when the class is applied to the `.hotgraphic-popup__item`.

**Comment by swashbuck** [comment]
> This works as expected thanks @swashbuck. One thing to note, Hotgraphic has separate `_classes` for [popup](https://github.com/adaptlearning/adapt-contrib-hotgraphic/blob/d4241ec2bcf965a12e25f30bac1fe071eb56ed50/example.json#L38) and [item](https://github.com/adaptlearning/adapt-contrib-hotgraphic/blob/d4241ec2bcf965a12e25f30bac1fe071eb56ed50/example.json#L43). Would we want to do the same here for consistency?
> 
> Although I do find it odd that the Hotgraphic popup `_classes` is associated with the graphic when the class is applied to the `.hotgraphic-popup__item`.

Thanks, @kirsty-hames . I agree that we should align with Hotgraphic's classes implementation, as flawed as it is. I'll add a new `_classes` property to each Hotgrid item's `_graphic` object. Then, maybe in the future, we can look into changing both Hotgraphic and Hotgrid's implementation so that it makes more sense.

**Comment by swashbuck** [comment]
@kirsty-hames @oliverfoster These changes have been made. Ready for re-review.

**Review by kirsty-hames — APPROVED** [review]
Thanks @swashbuck - works as expected.

**Pull request merged**
